name: country_flags
description: A Flutter package to show a flag icon from a ISO country code.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^1.0.3

dev_dependencies:
  very_good_analysis: ^3.0.1

flutter:
  assets:
    - res/

